### ISSUE TITLE
Scrolling a UITableView does not trigger nextResponder

### ISSUE THREAD

**Issue by ghost** [MitchellMalleo/APIdleManager#2]
When scrolling a UITableView this should cause the timer to reset. However, scrolling the uitableview does not trigger a nextResponder event which means that the last interacted time is not reset.

**Comment by MitchellMalleo** [comment]
Hey virtu-bjost,

Since a UITableView inherits from UIScrollView, you should be able to implement the delegate method `- (void)scrollViewDidScroll:(UIScrollView *)scrollView`, and in that method make sure you call `[[APIdleManager sharedInstance] didReceiveInput];` in your `- (void)scrollViewDidScroll:(UIScrollView *)scrollView` implementation to reset the timer.

If you have any questions let me know!

**Comment by ghost** [comment]
I ended up adding in `sendEvent` in `UIApplication` and using that.
